extends Node
class_name MomentumComponent

## Phase 2.4: combat resource rhythm — build-and-spend Momentum.
##
## Generated by confirmed hits (per attack_id grant), drained by taking
## damage, refunded by kills and perfect-dodges. A combo_multiplier
## sustains while you keep landing hits and decays after a no-hit window.
##
## process_mode = PROCESS_MODE_PAUSABLE — momentum pauses with the game.
##
## UI hookup deferred to Phase 6.1. Specials gating deferred to Phase 2.x
## once player play-tests the build curve and reports what feels right.

signal momentum_changed(value: float, capacity: int)
signal momentum_spent(amount: float, reason: StringName)
signal combo_multiplier_changed(value: float)

@export var capacity: int = 100
@export var decay_per_sec: float = 8.0
@export var damage_taken_drain: float = 25.0
@export var kill_grant: float = 5.0
@export var perfect_dodge_grant: float = 40.0

# Combo multiplier — sits in [1.0, max_combo]; +0.1 per landed hit, decays
# after combo_decay_delay_ms with no hit.
@export var max_combo: float = 2.0
@export var combo_grow_per_hit: float = 0.1
@export var combo_decay_per_sec: float = 0.4
@export var combo_decay_delay_ms: int = 1200

# Per-attack-id grants. Keys are StringName attack_ids; values are
# base momentum amounts. Wide attacks (whirlwind/spin) get per-target
# grants; resolve_hit fires once per victim so the natural accumulation
# matches "more targets, more momentum".
var _grants: Dictionary = {
	&"swing_a": 5.0,
	&"swing_b": 8.0,
	&"swing_c": 15.0,
	&"swing_d": 12.0,
	&"swing_e": 10.0,
	&"branch_slam": 20.0,
	&"branch_uppercut": 15.0,
	&"branch_spin": 12.0,
	&"power_strike": 15.0,
	&"whirlwind": 8.0,
	&"charged_slash": 25.0,
	&"dash_strike": 10.0,
	&"piercing_shot": 10.0,
	&"arrow_rain": 6.0,
	&"sniper_shot": 22.0,
	&"shadow_step": 10.0,
	&"projectile": 4.0,
}

var _current: float = 0.0
var _combo: float = 1.0
var _last_hit_usec: int = 0


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_PAUSABLE


func _process(delta: float) -> void:
	# Slow ambient decay so a long pause without hits drains some momentum.
	# Tuned low so a player who is mid-encounter doesn't feel punished.
	if _current > 0.0:
		var prev = _current
		_current = max(0.0, _current - float(decay_per_sec) * delta)
		if not is_equal_approx(prev, _current):
			momentum_changed.emit(_current, int(capacity))

	# Combo multiplier decay after no-hit window.
	if _combo > 1.0:
		var since_hit_ms: int = (Time.get_ticks_usec() - _last_hit_usec) / 1000
		if since_hit_ms > int(combo_decay_delay_ms):
			var prev_combo = _combo
			_combo = max(1.0, _combo - float(combo_decay_per_sec) * delta)
			if not is_equal_approx(prev_combo, _combo):
				combo_multiplier_changed.emit(_combo)


## Owner calls this on each confirmed hit landed BY this entity. attack_id
## drives the per-attack grant; final_feedback can boost the grant on
## CRIT (we apply 1.3x).
func on_hit_landed(attack_id: StringName, was_crit: bool) -> void:
	var base: float = float(_grants.get(attack_id, 4.0))
	var bonus: float = 1.3 if was_crit else 1.0
	var amount: float = base * bonus
	_credit(amount, attack_id)
	# Bump combo multiplier — capped at max_combo.
	var prev = _combo
	_combo = clamp(_combo + float(combo_grow_per_hit), 1.0, float(max_combo))
	_last_hit_usec = Time.get_ticks_usec()
	if not is_equal_approx(prev, _combo):
		combo_multiplier_changed.emit(_combo)


func on_kill() -> void:
	_credit(float(kill_grant), &"kill")


func on_perfect_dodge() -> void:
	_credit(float(perfect_dodge_grant), &"perfect_dodge")


func on_damage_taken() -> void:
	if _current <= 0.0 and is_equal_approx(_combo, 1.0):
		return
	var prev = _current
	_current = max(0.0, _current - float(damage_taken_drain))
	if not is_equal_approx(prev, _current):
		momentum_changed.emit(_current, int(capacity))
		momentum_spent.emit(prev - _current, &"damage_taken")
	# Damage breaks the combo back to 1.
	if _combo > 1.0:
		_combo = 1.0
		combo_multiplier_changed.emit(_combo)


## Returns true if the spend succeeded (sufficient momentum). Caller
## chooses whether to gate the special on the return value — Phase 2.4
## leaves gating off, so callers can just observe the spend signal for
## UI / SFX without blocking the action.
func try_spend(amount: float, reason: StringName) -> bool:
	if amount <= 0.0:
		return true
	if _current < amount:
		return false
	_current -= amount
	momentum_changed.emit(_current, int(capacity))
	momentum_spent.emit(amount, reason)
	return true


func current() -> float:
	return _current


func combo_multiplier() -> float:
	return _combo


func ratio() -> float:
	if capacity <= 0:
		return 0.0
	return _current / float(capacity)


func force_reset() -> void:
	_current = 0.0
	_combo = 1.0
	momentum_changed.emit(0.0, int(capacity))
	combo_multiplier_changed.emit(1.0)


func _credit(amount: float, reason: StringName) -> void:
	if amount <= 0.0:
		return
	var prev = _current
	_current = min(float(capacity), _current + amount)
	if not is_equal_approx(prev, _current):
		momentum_changed.emit(_current, int(capacity))
